CREATE TYPE levels AS ENUM('Trainee', 'Junior', 'Middle', 'Senior');

CREATE TABLE worker (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    BIRTHDAY DATE CHECK (BIRTHDAY > '1900-01-01'),
    SALARY BIGINT CHECK (SALARY >= 100 AND SALARY <= 100000),
    LEVEL levels NOT NULL
);

CREATE TABLE client (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL
);

CREATE TABLE project (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CLIENT_ID INT,
    START_DATE DATE,
    FINISH_DATE DATE,
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID)
);

CREATE TABLE project_worker (
    PROJECT_ID INT,
    WORKER_ID INT,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
);

CREATE SEQUENCE worker_seq START WITH 1;
CREATE SEQUENCE client_seq START WITH 1;
CREATE SEQUENCE project_seq START WITH 1;